### ISSUE TITLE
Set build var to default and add script for advanced users to change them

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#103]
Currently we have defined

```
BUILDDIR = "/workspaces/r-dev-env/build/"
TOP_SRCDIR = "/workspaces/r-dev-env/svn/"
```

with the idea that the basic workflow for building R should use `$BUILDDIR/r-devel` and `$TOP_SRCDIR/r-devel` and different versions of R could be built with `$BUILDDIR/$LABEL` and `$TOP_SRCDIR/$LABEL`, where $LABEL replaces "r-devel". A disadvantage of this approach is that it deviates from the approach documented in the R Dev Guide and the R-admin manual.  Also, we can no longer simply refer to "the build directory" and "the source directory", which complicates documentation.

So I think we should change the defaults to

```
BUILDDIR = "/workspaces/r-dev-env/build/r-devel"
TOP_SRCDIR = "/workspaces/r-dev-env/svn/r-devel"
```

Then the basic workflow for building R can use these environment variables directly, sticking to the objective of keeping things simple for new contributors. 

To build a different version of R a user just need to redefine these variables, which could be facilitated with a script. This should have a "barebones" interface, so that it is quick to switch between multiple working copies of R. It could work as follows:

```
$set_build_var r-devel-raw
The build variables have been set to:
BUILDDIR = "/workspaces/r-dev-env/build/r-devel-raw"
TOP_SRCDIR = "/workspaces/r-dev-env/svn/r-devel-raw"
```

**Comment by hturner** [comment]
Just testing the GitPod (via gitpod.io/#https://github.com/r-devel/r-dev-env/tree/update/gitpod-config). Annoyingly, GitPod uses the directory "workspace" rather than "workspaces", so for the GitPod we need

```
BUILDDIR = "/workspace/r-dev-env/build/r-devel"
TOP_SRCDIR = "/workspace/r-dev-env/svn/r-devel"
```

still - another advantage of using environment variables for this, as the docs stay the same.

**Comment by iaine** [comment]
Not sure if this complicates things but it may be possible to define a gitpod Dockerfile and yml files to install onto Gitpod?:
https://www.gitpod.io/docs/configure/workspaces/workspace-image#using-a-custom-dockerfile

Given the conversation above, it may be easier for documentation to have a check for /workspace/ or workspaces and reset the environment variables?

**Comment by hturner** [comment]
I wonder if it is possible to automatically detect the name of the workspace folder. I just tried local setup from a zip file and by default the zip file is name by the branch (e.g. r-dev-env-main or r-dev-env-devel), so it unzips to a folder of the same name. If you then open that in VSCode, the workspace folder is e.g. `/workspaces/r-dev-env-main/`. So detecting the workspace name when the environment variables are created could deal with both the Codespaces/GitPod difference and the zip issue.

I think the postCreateCommand will be run in the root of the workspace (i.e. the workspace folder), similarly bash will open there. So you can use `$PWD` to access the name of the workspace folder and use that in the scripts that set up the the environment variables, VSCode settings, etc.

**Comment by StarTrooper08** [comment]
we had removed .git file from dev container to untrack the source code we checkout using  svn so I think using pwd we might unable to get pwd as /workspaces/r-dev-env-main/.

**Comment by StarTrooper08** [comment]
> Not sure if this complicates things but it may be possible to define a gitpod Dockerfile and yml files to install onto Gitpod?: https://www.gitpod.io/docs/configure/workspaces/workspace-image#using-a-custom-dockerfile
> 
> Given the conversation above, it may be easier for documentation to have a check for /workspace/ or workspaces and reset the environment variables?

The files are ready but unable to get things working as expected right now.

**Comment by hturner** [comment]
This issue is fixed for the GitHub codespace. Fixing it in a more general way for GitPod/other situations can be moved to a separate issue.

**Comment by hturner** [comment]
#158 fixed this for Gitpod and should be general enough to fix for the local setup from a zip file (untested).
