### ISSUE TITLE
Updates to Update Source section

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#108]
https://via.hypothes.is/https://contributor.r-project.org/r-dev-env/tutorials/update_source/

**Comment by StarTrooper08** [comment]
Is it point 7 or 2 cases for 5 point?

>
>#### 5)  Rebuild and check with the updates

>Te rebuild R with the latest changes from the R Core Team and any local changes you have kept, go to the build directory and >to build and check R

>```bash
>cd $BUILDDIR
>make 
>make check
>```

>If the check fails, this will be due to recent changes made by the R Core Team. See [SVN Help](link) for how to revert to a >version that passes check.
>
