### ISSUE TITLE
Missing Documentation Image

### ISSUE THREAD

**Issue by iaine** [r-devel/r-dev-env#113]
The Starting Codespace page on https://contributor.r-project.org/r-dev-env/tutorials/creating_codespace/ appears to be missing the first image. 

<img width="284" alt="codespaces" src="https://github.com/r-devel/r-dev-env/assets/7142803/3231599b-dce6-426d-800c-30594ad5dcc8">

The file seems to be present in the repo so maybe just a build issue?

**Comment by hturner** [comment]
I've also added some changes to the wording here: https://via.hypothes.is/https://contributor.r-project.org/r-dev-env/tutorials/creating_codespace/.

**Comment by StarTrooper08** [comment]
The image added updated docs on  branch update/docs.
Right now following https://via.hypothes.is/https://contributor.r-project.org/r-dev-env/tutorials/creating_codespace/  and  updating other areas of docs.
