### ISSUE TITLE
which_r version R version choice validation

### ISSUE THREAD

**Issue by iaine** [r-devel/r-dev-env#127]
When I use which_r in the devel branch on codespace and choose R, I can enter incorrect numbers without it being caught.

<img width="931" alt="Screenshot 2024-06-14 at 10 32 11" src="https://github.com/r-devel/r-dev-env/assets/7142803/6005a0dd-6835-4256-8a27-0516424493f2">

I would expect if choosing a value higher than the environments to have a warning. Maybe a simple add an else to the blocks in lines 36 - 40:
'''
if [[ ! "$choice" =~ ^[1-9]$ ]]; then
  echo "Invalid choice. Please enter a number between 1 and $(($counter - 1))"
  exit 1
elif [[ "$choice" > $counter ]]; then
  echo "Invalid choice. Please enter a number between 1 and $(($counter - 1))"
  exit 1
fi
'''
?

Otherwise the script returns with a path to an R` that does not exist.

**Comment by StarTrooper08** [comment]
Thanks! yeah we need to add this to handle the error properly.

I think we can shift the R version to default R if user enters outside of the options. And rerun the script for user to change R console version.

**Comment by hturner** [comment]
Also note the range is incorrect if you enter an invalid choice when there is only one option:

```
@hturner ➜ /workspaces/r-dev-env $ which_r
Which version of R should be used in new R terminals?
  1. R 4.4.0 (release version built into this container)
Enter the number corresponding to the selected version: 0
Invalid choice. Please enter a number between 1 and -1
``

**Comment by iaine** [comment]
The script now assigns to the system R if an invalid number is given.
