### ISSUE TITLE
Document LiveShare

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#135]
At the R Contribution Working Group meeting, @StarTrooper08 mentioned LiveShare as a feature. This was used at the R Project Sprint, but we don't document this anywhere. 

We should add a new LiveShare subsection to the Container Setup section that documents starting and stopping a LiveShare session, with screenshots - similar to the [official docs](https://docs.github.com/en/codespaces/developing-in-a-codespace/working-collaboratively-in-a-codespace) but they don't need to install the extension.

**Comment by StarTrooper08** [comment]
The official document for Live Share doesn't mention the read-only and read/write options. Maybe I can add that to the r-dev-env docs briefly.
![image](https://github.com/r-devel/r-dev-env/assets/72031540/eb212794-5a96-40b9-9a6f-ceecf04dbb69)
