### ISSUE TITLE
Gitpod VSCode Extension Settings sync

### ISSUE THREAD

**Issue by StarTrooper08** [r-devel/r-dev-env#153]
Currently Gitpod works properly and let's user build R from source code.

But other features like switching interactive console R version using which_r script. And this is due sync problem with R extension with settings json file inside gitpod workspace.

Till now the settings file is getting modified using the scripts but still sync problem is there.

I build R-devel from source code and tried to switch from default R version in container. But it was not getting switched to r-devel one. But the settings json file was getting modified seemlessly from usr/bin/r(default R ver) to r-devel ver.

**Comment by iaine** [comment]
I'm not seeing that on the update/gitpod-setup branch built on gitpod. I am seeing several errors due to /home/vscode not being available.

**Comment by StarTrooper08** [comment]
Sorry for delay, I was working on this feature and the adding paths is making things complicated and may work on gitpod but might break in github codespace. So trying out that can work on both gitpod as well as codespace.

**Comment by StarTrooper08** [comment]
The which_r is working, yet it has to updated with the settings json file. That might work after the relevent changes.

But not sure why set_build_r is not working now.

**Comment by hturner** [comment]
This is fixed by #158
