### ISSUE TITLE
CONTAINER_VERSION not working in Gitpod

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#167]
When I ran the container in GitPod from the `update/common env setup` branch (now closed), the `CONTAINER_VERSION` was not found when the welcome message was created. This may be a temporary issue with the container image not matching the setup code, but opening this issue so we can check this when the container is rebuilt by GH actions.

**Comment by iaine** [comment]
I have just built the code  on gitpod using the optimize-docs-images code and I'm not seeing the Container Version:
Welcome to the R Dev Container v

**Comment by StarTrooper08** [comment]
Solved by PR number : #171
