### ISSUE TITLE
Release version v0.3

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#181]
Checklist for release:

 - [x] Update NEWS file
 - [x] Update CITATION.cff
 - [x] Update VERSION
 - [x] In devcontainer.json, update `"image": "ghcr.io/r-devel/r-dev-env:devel"` to `"image": "ghcr.io/r-devel/r-dev-env:main"`,,
 - [x] Make PR to main branch - needs approving review!
 - [x] Make sure docker container is rebuilt
 - [x] Test container and fix any issues
 - [x] Make GitHub release
 - [ ] Rebuild docs

**Comment by StarTrooper08** [comment]
New Version release NEWS.md

v0.3

Gitpod Setup
Github Actions to build Docker Image for Gitpod workspace
Gitpod VSCode Extension Settings Sync
which_r R version choice validation
Local Setup Permission Issue solved and configured helper scripts to work properly on local devcontainer setup.
Workflow to optimize docs images

Docs :
Added Gitpod Documentation
Restructured overall Documentation
Updated Index Readme.md

**Comment by hturner** [comment]
I don't think "- Gitpod VSCode Extension Settings Sync" needs to be a separate point as that is part of the Gitpod setup. 

Similarly "-Updated Index Readme.md" doesn't need to be a separate point as that is part of "-Restructured overall Documentation". In fact maybe "Added Gitpod Documentation" is enough.

The aim of the NEWS is to communicate the main changes from a user point of view, so they don't need a detailed breakdown of the tasks this involved.

**Comment by hturner** [comment]
It looks like we no longer need to rebuild the docs after making a release - the version number automatically updates in the mkdocs documentation as well as on the README. I'll update the issue template!
