### ISSUE TITLE
Set and print out environment variables

### ISSUE THREAD

**Issue by jamestripp** [r-devel/r-dev-env#2]
Set the environment variables in the docker file and print these out on start

**Comment by jamestripp** [comment]
One way to do this may be to edit the .bashrc or similiar

**Comment by hturner** [comment]
The script to do this is in https://github.com/r-devel/r-dev-env/blob/main/scripts/add_to_bashrc.sh but it seems this is no longer run at the start. 

I think a welcome message is a nice feature, so it would be good to reinstate this, however `BUILDDIR` and `TOP_SRCDIR` are now defined in the Dockerfile (https://github.com/r-devel/r-dev-env/blob/dev-container/Dockerfile) so we don't need to do that in the `add_to_bashrc.sh` script.

**Comment by hturner** [comment]
Fixed in #56 (need to add commands to print welcome message to bashrc so that message gets printed in the terminal opened at start-up - other background scripts can be run with PostCreateCommand)
