### ISSUE TITLE
Correct "Open in GitHub Codespaces" button

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#21]
When I launch the workspace from the Code button > Codespaces tab > ... > New with options I see 

![image](https://github.com/r-devel/r-dev-env/assets/3343008/6ea596a4-8be5-4e29-85eb-a22aade2f318)

But when I open the workspace with the button in the README I see

![image](https://github.com/r-devel/r-dev-env/assets/3343008/c81f570c-f919-4751-9bb6-4e6b7900ed3a)

Can we correct the README button so it opens the workspace as in the first screenshot?

**Comment by jamestripp** [comment]
I have checked the current main branch and this is fixed.
