### ISSUE TITLE
Keep system library clean

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#25]
Currently the Dockerfile installs the **languageserver** package in the system library: https://github.com/r-devel/r-dev-env/blob/dev-container/Dockerfile#L18

On Slack I suggested that we manage without the **languageserver** package to avoid any conflict with base packages or any behaviour that is not reproducible with vanilla R. On reflection, I think it is okay to have it installed as people can always choose to use vanilla R by starting R in the bash terminal.

However, we should install the **languageserver** package into a separate library from the main system library. Otherwise when we rebuild R and overwrite the system install of R this means we have R 4.4 in the system, but still a lot of packages built under R 4.1 in the system library. We might do this by running some R code once the container has started. There are some pointers here: https://jozef.io/r300-language-server-setup/. I am not sure we will want to use their **languageserversetup** package directly as we will want to incorporate this in the container set up/start up, but I think we want to follow their general approach (maybe look inside their functions to see what the code does).

**Comment by hturner** [comment]
Thinking some more, a separate library doesn't completely solve the issue as the package build should match the R version. So we would need to at least reinstall **languageserver** when we build R-devel for the first time and the package or its dependencies may need rebuilding when R-devel is re-built, depending what people modify in base R. This could get messy as it won't be handled by `make` and slow down iterative development. So let's try not using **languageserver** at all and see how we get on.

**Comment by hturner** [comment]
I've had a closer look at the R extension settings (https://github.com/REditorSupport/vscode-R/wiki/Extension-settings) and it actually allows us to define two versions of R: `r.rpath.linux` for running background processes and `r.rterm.linux` for using in R terminals. I think this solves our issue here: we can set `r.rpath.linux` to a stable version of R, with **languageserver** installed and then set `r.rterm.linux` to the version that we have built (either relying on the PATH or by editing the settings.json file, see also discussion #50).

**Comment by jamestripp** [comment]
@StarTrooper08  These options can be changed in the container.dev file (for example, see https://github.com/r-devel/r-dev-env/commit/877bfd6e400115dfea3338ac1f0bf1758dfa85e9 ). It might be cleaner to make the modifications in the 25-keep-system-library-clean branch and then merge these using a PR request. Thanks!

**Comment by jamestripp** [comment]
@StarTrooper08 , thanks for fixing this in https://github.com/r-devel/r-dev-env/commit/412b31dbd0b2fff96e07b80740d8e2b428549972  and suggesting I look at the change.

I had not realised that the user is now unable to open R via the R plugin (either via the not attached button at the bottom toolbar or via the command pallette). This could be disorientating for the user so I suggest we leave this issue open and discuss this as a group.

One possible workaround is to syslink the R version in the OS to the new path. The command can be run after the devcontainer starts (or within the image itself) 

`
mkdir -p /workspaces/r-dev-env/bin/R/bin/ && ln -s /usr/bin/R /workspaces/r-dev-env/bin/R/bin/R
`

**Comment by hturner** [comment]
Fixed in #68: can now build R and switch to it before opening a new terminal. Only the default version of R has languageserver installed so the built R has a clean library, but it is still possible to use basic VS code/R extension interactions, e.g. sending code from .R files to the R terminal with Ctrl/Cmd + Enter.
