### ISSUE TITLE
Add version number to welcome message

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#27]
When we have the welcome message #2 and start releasing versions of the devcontainer, it would be good to add the version number to the welcome message.

I'm not sure of the best way to do this - ideally the version number would be defined in one place that is then picked up wherever else it is used, so it is easier to maintain. This is why I am making a separate issue from #2 as this will take more work than simply changing the message text.

**Comment by jamestripp** [comment]
Good idea!

I'm not sure exactly how to do this. An ideal workflow would be to push the version number in the commit and then have a release created and somehow include that in the image.

There are actions to create a release when pushing the version number

https://github.com/elgohr/Github-Release-Action

and to add a tag to the docker image. 

https://stackoverflow.com/questions/66017161/add-a-tag-to-a-docker-image-if-theres-a-git-tag-using-github-action

This needs some additional thought. Thanks for raising the issue.

**Comment by jamestripp** [comment]
We now have the version specified in a file called VERSION and this is loaded into the container image and displayed in the welcome message. The pull request for this is https://github.com/r-devel/r-dev-env/pull/71
