### ISSUE TITLE
Look into use of dotfiles

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#28]
Can we use the dotfiles feature of codespaces to simplify customisations to `.bashrc`? https://docs.github.com/en/codespaces/customizing-your-codespace/personalizing-github-codespaces-for-your-account#dotfiles

**Comment by jamestripp** [comment]
I have just tried this and my dotfiles are not being copied over. I would err away from this, it looks like each user would need to have a personal dotfiles repo.

Happy to be corrected though.

**Comment by hturner** [comment]
Okay, thanks for looking into this.
