### ISSUE TITLE
Use a linter that follows R core guidelines

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#49]
Currently the linter in VS code shows the indentation in [R/trunsrc/utils/](https://svn.r-project.org/R/trunk/src/library/utils/R/askYesNo.R) as being incorrect.

Ideally we would have a linter that does not complain about existing R code in base R, since R Core do not want changes in a patch that are just altering the style.

To investigate: What linter is currently used? Is it https://cran.r-project.org/web/packages/lintr/index.html? Can we adapt it?

Note that relying on an add-on package presents similar issues as discussed in #25.

**Comment by hturner** [comment]
Yes, the linting is done with **lintr** via **languageserver** and we can customise it: https://github.com/REditorSupport/vscode-R/wiki/Code-linting.

**Comment by jamestripp** [comment]
We can configure the lintr options via a .lintr file (a relevant screenshot from the lintr vignette is below). That gives us options for changing the settings if they deviate from best practice for the R source code.

![image](https://github.com/r-devel/r-dev-env/assets/5781056/78afa1fb-661f-417c-9bed-a4099a825378)

**Comment by hturner** [comment]
I had a look at an example file from the R sources (http://svn.r-project.org/R/trunk/src/library/stats/R/anova.R), where the current linter shows many issues. I could customise the linter a little bit to make some of these issues go away, but some issues were unresolvable, e.g.
 *  open curly brace on its own line (not one of the options in https://lintr.r-lib.org/reference/brace_linter.html)
 *  tabs instead of spaces for indent
 *  no space after comma
 *  closing bracket on new line
 *  mix of hanging and block indentation, or inconsistent number of spaces in indents
Part of the problem is that even within one function, different conventions may be used. Contributors should not make stylistic changes to lines of code that they are not changing, so all the linter errors are a distraction.

So I think it is better for us to turn the linter off. This can be done by changing the setting "r.lsp.diagnostics" to false.
(c.f. https://stackoverflow.com/questions/68858490/disable-r-linting-in-vscode).

If you do this in an active codespace, you need to restart to see the effect. Hopefully we can make this the setting from the start, I think we are already changing some settings in the container.

**Comment by hturner** [comment]
The linter was disabled in v0.2 and screenshots have since been updated so no longer show linting problems.
