### ISSUE TITLE
Allow compilation of multiple R versions

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#50]
Following comment from @gmbecker that this is a desirable feature, we should revisit this.

Potential solutions
1.  Use symlinks to define which version of R should come first in the path
2.  Set `r.rterm.linux` in the `settings.json` (https://github.com/REditorSupport/vscode-R/wiki/Extension-settings)

Re the second option, the file we would wish to edit is in `/home/vscode/.vscode-remote/data/Machine/settings.json` (see https://github.com/orgs/community/discussions/27142). 

Either way, we should provide a tool for the user that is easy to run from the terminal, e.g.

```switch R-devel```

would switch to R-devel. This would depend how we organize multiple builds. Say we have

$BUILDDIR/R-devel-latest/bin/R
$BUILDDIR/R-devel-mine/bin/R
$BUILDDIR/R-3.4.0/bin/R

etc, where the tag "R-devel-latest", "R-devel-mine", etc is a tag that the user chooses. Then they would switch with `switch R-devel-mine`. We might corresponding want

$SVNDIR/R-devel-latest
$SVNDIR/R-devel-mine

etc, which would be a slight change to what we have now (where we have hard-coded "R-devel" in the path).

Can we open multiple R terminals in VS Code that use different R versions? (This would be another advantage over RStudio if so). If so, we might want the user interface to be `open R-devel-mine` to open an R terminal with that version of R.

**Comment by hturner** [comment]
@gmbecker suggested we should configure with `--prefix=$INSTALLDIR/R-version/` so that `make install` installs to that place, but I think it is not necessary to do the install step.

When we discussed previously with @mmaechler he suggested we could just run `make` and then point to `$BUILDDIR/bin/R` to use the version of R we want, when we are working in an exploratory way, building and testing different versions.

**Comment by mmaechler** [comment]
Indeed, I have many dozens of R versions simultaneously available on my computers by using the above, and  "point to" being implemented by symbolic links in a to another `bin` directory that is part of `$PATH`.
E.g. `$HOME/bin` being part of `$PATH`:
```
cd $HOME/bin
ln -s   <...>/R-4.2.3-build/bin/R  R-4.2.3
```
creates an executable  `R-4.2.3`   and so I have executable  R-<x>.<y>.<z> in my PATH for many x, y, and z, and also `R-devel`
(even half a dozen *differently* configured versions of R-devel ..).

**Comment by hturner** [comment]
Thanks @mmaechler. So I think possibly both approaches I mentioned are useful: define symbolic links, then provide a tool to make it easy to switch the R version used by the R extension based on a given symbolic link.

I have taken a closer look at the options for the extension (https://github.com/REditorSupport/vscode-R/wiki/Extension-settings) and there is an option `r.alwaysUseActiveTerminal` - this might be helpful for switching between two versions of R that are running in different terminals. So we should explore defining custom settings in the container - one thing to check is whether (an advanced) user could override whatever settings we define (they should be able to!).

**Comment by jamestripp** [comment]
Re syslinks, this does seem to work.

https://github.com/r-devel/r-dev-env/blob/be13c3e79bf6634c72ee7d287b481eb3805f5fef/tutorials/build_and_install_r.sh

We could adapt this, including the above modifications, to more easily install and switch between versions of R.

It looks like we can add options via the json command in bash https://stackoverflow.com/questions/73867739/how-to-change-vs-code-settings-from-terminal-bash.
