### ISSUE TITLE
Combine all project files in a single branch

### ISSUE THREAD

**Issue by jamestripp** [r-devel/r-dev-env#58]
Our files are currently spread across three branches: main, dev-container, website. The dev-container and website branches use github actions which are triggered on commits to the respective branches. Code from main is included in our releases and there is a need for central resources available from main to the dev-container (version number) and website (tutorials).

One solution so this is to have all the files in one main branch, then trigger the github actions via the content of the commit message.

**Comment by jamestripp** [comment]
I've submitted a pull request which bring the dockerfile into the devel repository and trigger the image build using a string in the commit message head

https://github.com/r-devel/r-dev-env/pull/61

**Comment by hturner** [comment]
#61 merged in now, so it is just the website part to work on to close this issue.

**Comment by hturner** [comment]
#64 fixed the website part: website source is now in main branch (or devel for upcoming version) and deployed to gh-pages.
