### ISSUE TITLE
Consider ways to build website

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#59]
For now we will build content in markdown files. Consider whether to then use Quarto to build website or another tool, e.g. https://www.mkdocs.org/.

**Comment by jamestripp** [comment]
Thanks for looking into mkdocs, Atharva. You're absolutely right. I've put together a test with the GitHub actions file.

We can either build to gh-pages or into main. I suggest the former so we keep the main branch clean. Someone downloading a release probably doesn't need to have the build website.

https://github.com/jamestripp/mkdocs_website_example
https://jamestripp.github.io/mkdocs_website_example/

@StarTrooper08 , I would be happy for you to try this out on a branch. I suggest we use the Read the Docs theme and port across the existing documentation you have put together.

**Comment by jamestripp** [comment]
You could probably add a bash command into the github action. Something like

`
sed -i '1i new text' <(sed '1d' README.md) > docs/index.md
`

**Comment by jamestripp** [comment]
Actually, simpler than I thought. You can just cat to docs/index.md

`
name: build_site
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - run: cat README.md > docs/index.md
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
`

**Comment by hturner** [comment]
This is now implemented in #64 and #65, deployed at https://contributor.r-project.org/r-dev-env/
