### ISSUE TITLE
Using latest R version

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#84]
We should update the version of R used in the container to use the latest version.

Can this be automated somehow - that the container will always be built with the latest version of R?

If not, we should document how it can be updated, so we can quickly update the version of R when a new version is available.

**Comment by hturner** [comment]
Fixed by #87.

**Comment by StarTrooper08** [comment]
If we mention devel tag in devcontainer.json it works and has R 4.4.0 version.
![image](https://github.com/r-devel/r-dev-env/assets/72031540/f3bf6848-55e4-44c4-9a5d-aa60fcdbc006)

**Comment by StarTrooper08** [comment]
I've updated it 
Commit :  https://github.com/r-devel/r-dev-env/commit/20d371038801f8dc81740ab97ff371bb3406455d

**Comment by hturner** [comment]
Okay. I think it may be better to have something that doesn't depend on the branch name so that when we eventually merge in to the main branch it will use the stable release version and not the continually evolving devel version. Can you try to make it work so it uses the version number? Maybe something like:

```
"image": "ghcr.io/r-devel/r-dev-env:v${localEnv:VERSION}",
```

Otherwise we could add updating the image field of devcontainer.json to a checklist of things to do when releasing a new version (which we might implement as a GitHub issue template).

**Comment by StarTrooper08** [comment]
We can just have  2 version  of container right  now
Like for main branch we can have stable/latest version of container and for devel we can keep devel version for devel branch. 

Earlier due to PR merging  we have 10-12 different versions of  containers  created in  repo  package
https://github.com/r-devel/r-dev-env/pkgs/container/r-dev-env

We can declutter package section and just keep 2 version of  container for now

**Comment by hturner** [comment]
Having just a devel and stable/latest version sounds a good idea. 

I'm not quite sure how it works when we want to open a codespace based on a branch that changes the Dockerfile/devcontainer.json - presumably we need to build a container in that case for testing? Maybe the build can just be tagged by the branch name?
