### ISSUE TITLE
Disconnect the repository from git

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#85]
Currently the workspace is connected to the r-devel/r-dev-env repository, so when a user checks out the R sources from SVN, these files are tracked as modified files:

![image](https://github.com/r-devel/r-dev-env/assets/3343008/dd4b9d0a-1b9b-435c-bd2a-1f5796ea9b50)

This is not helpful to the user, who will not be making any commits to the r-dev-env repo. Also, after a while, error messages start appearing from the git extension, because so many uncommitted changes have been made.

So I think we should disconnect the workspace from the git repo. I think the simplest way to do this is to delete the `.git` file after the codespace is first started:

```sh
cd /workspaces/r-dev-env
rm -rf .git
```

Then files will no longer be tracked.

**Comment by StarTrooper08** [comment]
Yes rm -rf .git cmd will work here.
We can add this to codespace scripts that we have created for welcome_msg, setting r terminal path etc.

Idea here is to rm .git dir when codespace is started/created something like that.
I will try it and create a PR.

**Comment by hturner** [comment]
Closed by #88.
