### ISSUE TITLE
Check size of screenshots

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#91]
Ideally images should be <100kb so the doc pages load quickly. It would be worth reviewing the screenshots after fixing issue #49 (turning the linter off as in https://github.com/r-devel/r-dev-env/issues/49#issuecomment-1889621409 will change the appearance of R scripts in VS Code).

Images can be optimized in R, for some example code, see https://github.com/r-devel/r-project-sprint-2023/blob/main/participants/optimize_photo.R.

**Comment by hturner** [comment]
Incidentally, I'm not sure where the source images are that end up in https://github.com/r-devel/r-dev-env/assets. Is it possible to put them in a regular repo folder so it is easier to track them down?

**Comment by StarTrooper08** [comment]
Work to be Done:
Few updates for screenshot is remaining

**Comment by hturner** [comment]
Several of the new screenshots are ~200KB or more, so should be optimised.

**Comment by StarTrooper08** [comment]
Redirect #145
