### ISSUE TITLE
New sections in docs

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#96]
Can we split up the doc pages into more sections, to separate the tutorials from other docs as follows:

CONTAINER SETUP
* Starting Codespace
* Restarting & Stopping Codespace
* Local Setup

TUTORIALS
Remaining pages apart from Resources

RESOURCES
change Resources to index.md within this section if possible, or change to Useful Links

**Comment by StarTrooper08** [comment]
![image](https://github.com/r-devel/r-dev-env/assets/72031540/554f1d4c-264a-4706-bdde-0f449e7c8222)
The new design for docs looks like this currently 

I'll follow up on the above mentioned content split up.

**Comment by hturner** [comment]
Yes, so it would be great if you could create a new "Container Setup" section as mentioned above and simplify the Resources section (it doesn't need a sub-section).

**Comment by StarTrooper08** [comment]
I'm steadly working on this from Monday and I also found out that if we keep images inside the docs itself it loads quickly(actually it get cached). So right now I don't think we need to optimize it. Earlier it use to fetch the images from github assets storage that was the reason may be it use to take time to load.

Branch - https://github.com/r-devel/r-dev-env/tree/update/docs
![image](https://github.com/r-devel/r-dev-env/assets/72031540/90edce15-d986-4ed6-85bf-ac5ecf1baead)
